# Use an official Node.js image as a parent image
FROM node:14-alpine

# Set the working directory to /frontend
WORKDIR /frontend

# Copy the current directory contents into the container at /frontend
COPY package*.json ./

# Install any needed packages specified in package.json
RUN npm install

# Copy the rest of the application files
COPY . .

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Run app.js when the container launches
CMD ["npm", "start"]
