# Use an official Node.js image as a parent image
FROM node:14-alpine

# Set the working directory to /app
WORKDIR /frontend

# Copy the current directory contents into the container at /app
COPY package*.json ./

# Install any needed packages specified in package.json
RUN npm i

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Run app.js when the container launches
CMD ["npm", "start"]
