version: "3"

services:
  appointments:
    image: "${{ secrets.DOCKER_USERNAME }}/appointments:${{ github.sha }}"
    ports:
      - "7070:7070"
    networks:
      - devops-network

  doctors:
    image: "${{ secrets.DOCKER_USERNAME }}/doctors:${{ github.sha }}"
    ports:
      - "9090:9090"
    networks:
      - devops-network

  frontend:
    image: "${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}"
    ports:
      - "3000:3000"
    networks:
      - devops-network

networks:
  devops-network:
    driver: bridge
