apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointments-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: appointments
  template:
    metadata:
      labels:
        app: appointments
    spec:
      containers:
        - name: appointments
          image: muhammad444/appointments:latest
          ports:
            - containerPort: 7070
          env:
            - name: admin
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: username
            - name: admin123
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: password
