apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: doctors
  template:
    metadata:
      labels:
        app: doctors
    spec:
      containers:
        - name: doctors
          image: muhammad444/doctors:latest
          ports:
            - containerPort: 9090
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9090
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /readiness
              port: 9090
            initialDelaySeconds: 3
            periodSeconds: 3
          securityContext:
            runAsUser: 1000
            runAsGroup: 3000
          volumeMounts:
            - name: doctors-config-volume
              mountPath: /user
      volumes:
        - name: doctors-config-volume
          configMap:
            name: doctors-config
---
apiVersion: v1
kind: Service
metadata:
  name: doctors-service
spec:
  selector:
    app: doctors
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: LoadBalancer
