apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: doctors
  template:
    metadata:
      labels:
        app: doctors
    spec:
      containers:
        - name: doctors
          image: muhammad444/doctors:latest
          ports:
            - containerPort: 9090  # Assuming doctors microservice listens on port 8080

---
apiVersion: v1
kind: Service
metadata:
  name: doctors-service
spec:
  selector:
    app: doctors
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090  # Match the container port
  type: LoadBalancer

---
apiVersion: v1
kind: Secret
metadata:
  name: doctors-secret
type: Opaque
data:
  username: admin  # Use `echo -n 'your-username' | base64` to encode
  password: admin123  # Use `echo -n 'your-password' | base64`
