apiVersion: v1
kind: Secret
metadata:
  name: doctors-secret
type: Opaque
data:
  username: admin # Use `echo -n 'your-username' | base64` to encode
  password: admin123  # Use `echo -n 'your-password' | base64`
