name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker build -t muhammad444/appointments:latest ./appointments
      working-directory: ./appointments

  push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push Docker Image to Docker Hub
      run: |
        echo "dckr_pat_wZHh74yvw9P928ogs9wjFgZMTTo" | docker login -u "muhammad444" --password-stdin
        docker push muhammad444/appointments:latest
      env:
        DOCKER_CLI_ASK_PASS: "1"
