name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use
          docker buildx inspect
          
      - name: Build Docker image for Appointments
        run: docker buildx build --platform linux/amd64,linux/arm64 -t "muhammad444/appointments:latest" --push .

      - name: Build Docker image for Doctors
        run: docker buildx build --platform linux/amd64,linux/arm64 -t "muhammad444/doctors:latest" --push .

      - name: Build Docker image for Frontend
        run: docker buildx build --platform linux/amd64,linux/arm64 -t "muhammad444/frontend:latest" --push .

      # ... (other steps if needed)

