name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure Docker credentials
        run: |
          echo '{"auths": {"https://index.docker.io/v1/": {"auth": "'$(echo -n "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_TOKEN }}" | base64 -w 0)'"}}}' > $HOME/.docker/config.json

      - name: Build Docker image
        run: docker buildx build --platform linux/amd64,linux/arm64 -t "${{ secrets.DOCKER_USERNAME }}/appointments:${{ github.sha }}" --push .
