name: Build and Push Appointments Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use
          docker buildx inspect

      - name: Build and Push Appointments Docker Image
        run: |
          cd appointments
          docker buildx build --platform linux/amd64,linux/arm64 -t "muhammad444/appointments:latest" --push .
