name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image for Appointments
        run: docker buildx build --platform linux/amd64,linux/arm64 -t "muhammad444/appointments:latest" --push .

      - name: Build Docker image for Doctors
        run: docker buildx build --platform linux/amd64,linux/arm64 -t "muhammad444/doctors:latest" --push .

      - name: Build Docker image for Frontend
        run: docker buildx build --platform linux/amd64,linux/arm64 -t "muhammad444/frontend:latest" --push .

      # ... (other steps if needed)

