name: Docker Build and Push

on:
  push:
    paths:
      - 'doctors/**'
      - 'appointments/**'
      - 'frontend/**'
  pull_request:
    paths:
      - 'doctors/**'
      - 'appointments/**'
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: echo "${DOCKER_TOKEN}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

    - name: Build and Push Doctors Microservice
      if: contains(github.event.head_commit.modified, 'doctors/') || contains(github.event_name, 'pull_request')
      run: docker buildx build --platform linux/amd64,linux/arm64 -t muhammad444/doctors:${{ github.sha }} ./doctors --push

    - name: Build and Push Appointments Microservice
      if: contains(github.event.head_commit.modified, 'appointments/') || contains(github.event_name, 'pull_request')
      run: docker buildx build --platform linux/amd64,linux/arm64 -t muhammad444/appointments:${{ github.sha }} ./appointments --push

    - name: Build and Push Frontend Microservice
      if: contains(github.event.head_commit.modified, 'frontend/') || contains(github.event_name, 'pull_request')
      run: docker buildx build --platform linux/amd64,linux/arm64 -t muhammad444/frontend:${{ github.sha }} ./frontend --push
